/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package financebuddy;
import java.awt.CardLayout;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nepal
 */
public class DisplayExpense extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form LoginUi
     */
    int id;
    public DisplayExpense(int userid) {
                this.id = userid;
                System.out.println("DisplayExpense: "+ id);
        initComponents();
                                                          
    DefaultTableModel model = new DefaultTableModel();
    display_table.setModel(model); // Assuming 'display_table' is the name of your JTable

    model.addColumn("S.No");
    model.addColumn("Type");
    model.addColumn("Date");
    model.addColumn("Category");
    model.addColumn("Name");
    model.addColumn("Amount");

    try {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "system");
        Statement st = con.createStatement();
        String sql = "SELECT * FROM transactions where customer_id = ?";
        pst = con.prepareStatement(sql);
        pst.setInt(1, id); // Assuming id is the customer_id
        rs = pst.executeQuery();


        while (rs.next()) {
            String tid = rs.getString("tid");
            String type = rs.getString("t_type");
            String date = rs.getString("transaction_date");
            String category = rs.getString("t_category");
            String name = rs.getString("t_name");
            float amount = rs.getFloat("t_amount");

            model.addRow(new Object[]{tid, type, date, category, name, amount});
        }

        rs.close();
        st.close();
        con.close();
    } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_table = new javax.swing.JTable();
        display_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        display_btn1 = new javax.swing.JButton();
        display_btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finance Tracker");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(115, 152, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 460));

        display_table.setAutoCreateRowSorter(true);
        display_table.setBackground(new java.awt.Color(204, 204, 204));
        display_table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        display_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "S.No", "Type", "Date", "Category", "Name", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        display_table.setFocusable(false);
        display_table.setGridColor(new java.awt.Color(102, 102, 102));
        display_table.setRequestFocusEnabled(false);
        display_table.setSelectionBackground(new java.awt.Color(204, 204, 204));
        display_table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        display_table.setShowGrid(true);
        jScrollPane1.setViewportView(display_table);
        if (display_table.getColumnModel().getColumnCount() > 0) {
            display_table.getColumnModel().getColumn(0).setResizable(false);
            display_table.getColumnModel().getColumn(1).setResizable(false);
            display_table.getColumnModel().getColumn(2).setResizable(false);
            display_table.getColumnModel().getColumn(3).setResizable(false);
            display_table.getColumnModel().getColumn(4).setResizable(false);
            display_table.getColumnModel().getColumn(5).setResizable(false);
        }

        display_btn.setBackground(new java.awt.Color(115, 152, 242));
        display_btn.setForeground(new java.awt.Color(255, 255, 255));
        display_btn.setText("Show All ");
        display_btn.setFocusable(false);
        display_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_btnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Click the buttons to view");

        jPanel2.setPreferredSize(new java.awt.Dimension(1023, 42));

        jButton8.setText("Delete");
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Update");
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(115, 152, 242));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Display");
        jButton10.setFocusable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Add");
        jButton11.setFocusable(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton3.setText("Home");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton12.setText("Logout");
        jButton12.setFocusable(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton11)
                    .addComponent(jButton10)
                    .addComponent(jButton9)
                    .addComponent(jButton8)
                    .addComponent(jButton12))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        display_btn1.setBackground(new java.awt.Color(115, 152, 242));
        display_btn1.setForeground(new java.awt.Color(255, 255, 255));
        display_btn1.setText("Expense");
        display_btn1.setFocusable(false);
        display_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_btn1ActionPerformed(evt);
            }
        });

        display_btn2.setBackground(new java.awt.Color(115, 152, 242));
        display_btn2.setForeground(new java.awt.Color(255, 255, 255));
        display_btn2.setText("Income");
        display_btn2.setFocusable(false);
        display_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(display_btn)
                .addGap(18, 18, 18)
                .addComponent(display_btn1)
                .addGap(18, 18, 18)
                .addComponent(display_btn2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(display_btn)
                    .addComponent(display_btn1)
                    .addComponent(display_btn2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void display_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_btnActionPerformed
                                                  
    DefaultTableModel model = new DefaultTableModel();
    display_table.setModel(model); // Assuming 'display_table' is the name of your JTable

    model.addColumn("S.No");
    model.addColumn("Type");
    model.addColumn("Date");
    model.addColumn("Category");
    model.addColumn("Name");
    model.addColumn("Amount");

    try {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "system");
        Statement st = con.createStatement();
        String sql = "SELECT * FROM transactions where customer_id = ?";
        pst = con.prepareStatement(sql);
        pst.setInt(1, id); // Assuming id is the customer_id
        rs = pst.executeQuery();


        while (rs.next()) {
            String tid = rs.getString("tid");
            String type = rs.getString("t_type");
            String date = rs.getString("transaction_date");
            String category = rs.getString("t_category");
            String name = rs.getString("t_name");
            float amount = rs.getFloat("t_amount");

            model.addRow(new Object[]{tid, type, date, category, name, amount});
        }

        rs.close();
        st.close();
        con.close();
    } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }

    }//GEN-LAST:event_display_btnActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       UpdateFront update_ui = new UpdateFront(id);
        update_ui.pack();
        update_ui.setLocationRelativeTo(null);
        update_ui.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jButton10.setEnabled(false);       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        HomePageUi home_ui = new HomePageUi(id);
        home_ui.pack();
        home_ui.setLocationRelativeTo(null);
        home_ui.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        MainUi add_e = new MainUi();
        add_e.pack();
        add_e.setLocationRelativeTo(null);
        add_e.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
         // TODO add your handling code here:
         AddExpense add_e = new AddExpense(id);
        add_e.pack();
        add_e.setLocationRelativeTo(null);
        add_e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DeleteUi delete_ui = new DeleteUi(id);
        delete_ui.pack();
        delete_ui.setLocationRelativeTo(null);
        delete_ui.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_jButton8ActionPerformed

    private void display_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_btn1ActionPerformed
         DefaultTableModel model = new DefaultTableModel();
    display_table.setModel(model); // Assuming 'display_table' is the name of your JTable

    model.addColumn("S.No");
    model.addColumn("Type");
    model.addColumn("Date");
    model.addColumn("Category");
    model.addColumn("Name");
    model.addColumn("Amount");

    try {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "system");
        Statement st = con.createStatement();
        String sql = "SELECT * FROM transactions where t_type='expense' AND customer_id = ?";
        pst = con.prepareStatement(sql);
        pst.setInt(1, id); 
        rs = pst.executeQuery();
        while (rs.next()) {
            String tid = rs.getString("tid");
            String type = rs.getString("t_type");
            String date = rs.getString("transaction_date");
            String category = rs.getString("t_category");
            String name = rs.getString("t_name");
            float amount = rs.getFloat("t_amount");

            model.addRow(new Object[]{tid, type, date, category, name, amount});
        }

        rs.close();
        st.close();
        con.close();
    } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_display_btn1ActionPerformed

    private void display_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_btn2ActionPerformed
       DefaultTableModel model = new DefaultTableModel();
    display_table.setModel(model); // Assuming 'display_table' is the name of your JTable

    model.addColumn("S.No");
    model.addColumn("Type");
    model.addColumn("Date");
    model.addColumn("Category");
    model.addColumn("Name");
    model.addColumn("Amount");

    try {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "system", "system");
        Statement st = con.createStatement();
       String sql = "SELECT * FROM transactions where t_type='income' AND customer_id = ?";
        pst = con.prepareStatement(sql);
        pst.setInt(1, id); // Assuming id is the customer_id
        rs = pst.executeQuery();
        while (rs.next()) {
            String tid = rs.getString("tid");
            String type = rs.getString("t_type");
            String date = rs.getString("transaction_date");
            String category = rs.getString("t_category");
            String name = rs.getString("t_name");
            float amount = rs.getFloat("t_amount");

            model.addRow(new Object[]{tid, type, date, category, name, amount});
        }

        rs.close();
        st.close();
        con.close();
    } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_display_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton display_btn;
    private javax.swing.JButton display_btn1;
    private javax.swing.JButton display_btn2;
    private javax.swing.JTable display_table;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
